# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first1', '0002_sankey2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sankey2',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
